---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lazarus-operator
  namespace: lazarus-system
  labels:
    app.kubernetes.io/name: lazarus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: lazarus-operator
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
